import { describe, it, expect } from 'vitest'
import { userSourcesFor } from './constants'

// Regression test for #262 sub-bug B: on kubectl/local, dune-admin writes
// operator settings (including custom, non-schema keys) directly to
// UserGame.ini, so the "userGame" source IS a user override there. On AMP,
// UserGame.ini is regenerated by AMP itself — only "userGameOverrides" (the
// separate file dune-admin actually writes) and "amp" (curated settings
// written through the AMP API) represent real operator overrides (#212).
describe('userSourcesFor', () => {
  it('excludes userGame/userEngine on the amp control plane', () => {
    const sources = userSourcesFor('amp')
    expect(sources.has('userGame')).toBe(false)
    expect(sources.has('userEngine')).toBe(false)
    expect(sources.has('userGameOverrides')).toBe(true)
    expect(sources.has('amp')).toBe(true)
  })

  it('includes userGame/userEngine on kubectl', () => {
    const sources = userSourcesFor('kubectl')
    expect(sources.has('userGame')).toBe(true)
    expect(sources.has('userEngine')).toBe(true)
    expect(sources.has('userGameOverrides')).toBe(true)
    expect(sources.has('amp')).toBe(true)
  })

  it('includes userGame/userEngine on local', () => {
    const sources = userSourcesFor('local')
    expect(sources.has('userGame')).toBe(true)
    expect(sources.has('userEngine')).toBe(true)
  })

  it('includes userGame/userEngine when control is unknown/empty', () => {
    expect(userSourcesFor('').has('userGame')).toBe(true)
    expect(userSourcesFor('docker').has('userGame')).toBe(true)
  })
})
